### ISSUE TITLE
New algorithm, data structure or puzzle

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#1]
Just make new PR with algorithm implementation. Language doesn't matter. 
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by sayak119** [comment]
@ZoranPandovski I would like to work on this issue. And can I implement any algorithm ?

**Comment by ZoranPandovski** [comment]
@sayak119 Sure. Make PR with the one you choose and follow  https://github.com/ZoranPandovski/al-go-rithms#contribution .

**Comment by sayak119** [comment]
@ZoranPandovski i would like to work on the issue of updating the readme too

**Comment by jebinphilipose** [comment]
I would like to contribute to  this issue.

**Comment by ZoranPandovski** [comment]
@jebinphilipose You are welcome. Choose algorithm and make PR.

**Comment by stefanpie** [comment]
Will you also accept data structures as well for contributions

**Comment by ZoranPandovski** [comment]
@stefanpie Yes, also you can add puzzles if you like

**Comment by jebinphilipose** [comment]
Please review my PR (#8).

**Comment by tejas2005** [comment]
Hey, @ZoranPandovski can you please check my PR on Euclid's algorithm.

**Comment by jebinphilipose** [comment]
Please review my PR (#14) in which I updated the README.md file to include Coding Practice Sites section which was missing.

**Comment by tejas2005** [comment]
@ZoranPandovski can you reopen my pull request I accidentally closed them.Please help I am a newbie

**Comment by jebinphilipose** [comment]
Please review my PR (#23) in which I added the implementation of strong number and updated the README.md file accordingly.

**Comment by jebinphilipose** [comment]
Please review my PR (#24) in which I added the implementation of factorial in C and updated the README.md file accordingly.

**Comment by the-ethan-hunt** [comment]
Please review my PR( #34 ) where I have added Kadane's algo in python with a readme.md

**Comment by arijitkar98** [comment]
@ZoranPandovski Hi, I would like to contribute to this issue

**Comment by ZoranPandovski** [comment]
@arijitkar98 You are welcome.

**Comment by akshat14714** [comment]
@ZoranPandovski I would also like to work on this issue, and also want to implement new algortihms.

**Comment by ZoranPandovski** [comment]
@akshat14714 Sure, just choose algorithm and make PR

**Comment by arijitkar98** [comment]
Please review my PR (#39) where I have added Levenshtein Distance implementation in cpp.
