### ISSUE TITLE
New algorithm, data structure or puzzle

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#101]
Just make new PR with algorithm implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by ramanan12345** [comment]
# Python program to implement Pigeonhole Sort */
 
# source code : "https://en.wikibooks.org/wiki/
#   Algorithm_Implementation/Sorting/Pigeonhole_sort"
def pigeonhole_sort(a):
    # size of range of values in the list 
    # (ie, number of pigeonholes we need)
    my_min = min(a)
    my_max = max(a)
    size = my_max - my_min + 1
 
    # our list of pigeonholes
    holes = [0] * size
 
    # Populate the pigeonholes.
    for x in a:
        assert type(x) is int, "integers only please"
        holes[x - my_min] += 1
 
    # Put the elements back into the array in order.
    i = 0
    for count in range(size):
        while holes[count] > 0:
            holes[count] -= 1
            a[i] = count + my_min
            i += 1
             
 
a = [8, 3, 2, 7, 4, 6, 8]
print("Sorted order is : ", end = ' ')
 
pigeonhole_sort(a)
         
for i in range(0, len(a)):
    print(a[i], end = ' ')

**Comment by ramanan12345** [comment]
this alogrithm

**Comment by ZoranPandovski** [comment]
@ramanan12345 Sure go ahead, add that algorithm following the contribution guide. Thanks

**Comment by namish800** [comment]
@ZoranPandovski review PR https://github.com/ZoranPandovski/al-go-rithms/pull/186

**Comment by namish800** [comment]
@ZoranPandovski review PR https://github.com/ZoranPandovski/al-go-rithms/pull/186
