### ISSUE TITLE
Wrong algorithm for anagrams in C++.

### ISSUE THREAD

**Issue by sagarvijaygupta** [ZoranPandovski/al-go-rithms#1148]
**This is Error:**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

The given implementation in C++ may even consider `mggg` and `mmmg` as anagrams.

**Comment by ZoranPandovski** [comment]
Can you specify which one is that? Thanks

**Comment by sagarvijaygupta** [comment]
@ZoranPandovski I am talking about [AnagramStrings.h](https://github.com/ZoranPandovski/al-go-rithms/blob/master/puzzles/anagram/c%2B%2B/AnagramStrings.h)
