### ISSUE TITLE
Clean-up and merge multiple directories with N-queen implementation

### ISSUE THREAD

**Issue by Jay9596** [ZoranPandovski/al-go-rithms#1197]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

There are multiples directories with the same implementation.
- [backtracking/n-queens](https://github.com/ZoranPandovski/al-go-rithms/tree/master/backtracking/n-queens)
- [games/NQueensSolution](https://github.com/ZoranPandovski/al-go-rithms/tree/master/games/cpp)
- [puzzles/N-queens](https://github.com/ZoranPandovski/al-go-rithms/tree/master/puzzles/N-queens)

The need to be merged in a single directory.

**Comment by Jay9596** [comment]
The Tree implementation also has the same issue:
- [data-structures/Tree](https://github.com/ZoranPandovski/al-go-rithms/tree/master/data_structures/Tree)
- [data-structures/Trees](https://github.com/ZoranPandovski/al-go-rithms/tree/master/data_structures/Trees)
- [Tree](https://github.com/ZoranPandovski/al-go-rithms/tree/master/Tree)

**Comment by Jay9596** [comment]
I'll list out all issues that I can find so that contributors can take one and start solving. 
@ZoranPandovski , do you have any problems with this ?

**Comment by ZoranPandovski** [comment]
Yes, I know this. It would be good if we clean them up. Thanks @Jay9596
