### ISSUE TITLE
New data structure

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#123]
Currently we got few data structures so new PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by goksgie** [comment]
Hi there you can assign me on a Binary Tree and segment tree implementation using c++,

**Comment by ZoranPandovski** [comment]
@goksgie Sure, just make PR with the implementations
