### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#1284]
Implementation list should be updated with missing algorithms https://github.com/ZoranPandovski/al-go-rithms/blob/master/IMPLEMENTATIONS.md

**Comment by Pavlosdnds** [comment]
I am currently working on updating the IMPLEMENTATIONS.md.  So far, I've changed the Sort section to be depicted in alphabetical order, added missing links to implementations and fixed some typos in a couple of READMEs . Should I make a PR now and then work on the merged version or should I continue working on it and make a final PR when I'm done with making changes?
