### ISSUE TITLE
New sort and search algorithms

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#133]
We need more sort and search algorithms in any language. PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by Gupta-shifali** [comment]
Can I implement insertion sort in c++ @ZoranPandovski ??

**Comment by ZoranPandovski** [comment]
@Gupta-shifali Yes

**Comment by Deepak345** [comment]
can i implement interpolation search??

**Comment by DJAcquila** [comment]
Can I implement a bucketsort ?

**Comment by ZoranPandovski** [comment]
@Deepak345 @DJAcquila Yes, go ahead
