### ISSUE TITLE
Interview / Whiteboard Problems

### ISSUE THREAD

**Issue by saifserver** [ZoranPandovski/al-go-rithms#1545]
People appear for various interview in different domains and technology and get some of the best dodgy and unique questions which is expected to be solved by the candidate.
We can with collaboration make a collection of such questions and its solutions. After all this is to get your dream job. (maybe not) :wink:

**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

:raised_hand: P.S: If required I can personally devote time on this proposal to the repository.

**Comment by ZoranPandovski** [comment]
This is a great idea @saifserver. What is your main idea to proceed with this?

**Comment by rohitkrishna094** [comment]
So is it like an online repository thats similar to glassdoor? How would it be different compared to glassdoor or geekgsforgeeks etc which already have a ton of questions listed from many companies etc.

Just brainstorming. :)

**Comment by saifserver** [comment]
The websites mentioned give solutions for a specific problems related to directly applying the concepts of data structure and algorithms. I am trying to build a collections of questions that use those data structure and algorithms such as finding max sub-array of an array, tweet count given a data set, etc. Also getting solutions in multiple languages.

@ZoranPandovski I'm working to add few samples and a README. We can discuss further upon reviewing. Also can you add labels for contributions so that we get to hear more ideas from the community.

**Comment by ZoranPandovski** [comment]
Great please share them with everyone so we can get more ideas
