### ISSUE TITLE
New math algorithms

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#228]
We got few algorithms in math so new PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by npochhi** [comment]
Please check https://github.com/ZoranPandovski/al-go-rithms/pull/229

**Comment by nikhilhassija** [comment]
#234 - Towers of Hanoi in C++

**Comment by nikhilhassija** [comment]
#235 - Euclid's GCD in C++

**Comment by juan88** [comment]
#347 - Fast Exponentiation in Go.
