### ISSUE TITLE
Can I write Power(X,N) program in C,C++,Java, Python languages? By including both positive, negative exponent covering all edges cases. 

### ISSUE THREAD

**Issue by vamsireddy22** [ZoranPandovski/al-go-rithms#2439]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by vamsireddy22** [comment]
In Bit manipulations, there is no program for this. So, I decided to add it. Can I?

**Comment by dissayamas1** [comment]
n

**Comment by ZoranPandovski** [comment]
Perfect. Thanks @vamsireddy22

**Comment by vamsireddy22** [comment]
Thanks, will finish it to this night :)
