### ISSUE TITLE
New algorithms, data structures or puzzle 

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#245]
Just make new PR with algorithm, data structures or puzzle  implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by anshullahoti** [comment]
I will implement dfs in cpp.

**Comment by kushagra7589** [comment]
I am gonna implement the `O(nlogn)` implementation of Longest Increasing Sub-sequence.

**Comment by amankh99** [comment]
@ZoranPandovski I want to add two versions of edit distance problem. First having space complexity of O(m*n) and second O(min(m, n)) where m and n are length of two strings for which we want to calculate minimum edit distance. Please assign me this work.

**Comment by rohitrango** [comment]
I have added the Rod cutting dp problem in Python. Please refer to #303, and let me know of any changes that I may have to make. Thanks :smile:

**Comment by nghiaxlee** [comment]
I'd like to add LCS problem with O(n) memory space #
