### ISSUE TITLE
Add "hacktoberfest" tag to the repository

### ISSUE THREAD

**Issue by AlanJereb** [ZoranPandovski/al-go-rithms#2498]
Hacktoberfest's website says :
```Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.```

@ZoranPandovski  Please add hacktoberfest tag to the repo and not only to issues, otherwise it won't count.

**Comment by ZoranPandovski** [comment]
Hi @alanfgn I am confused, what should be added to the repository apart from the label?

**Comment by ZoranPandovski** [comment]
Done. Tag added.
