### ISSUE TITLE
Can I add Support Vector Machine Algorithm to this repository as contribution to Hacktoberfest!

### ISSUE THREAD

**Issue by taneemishere** [ZoranPandovski/al-go-rithms#2515]
**This is a(n):**

- [ ✔] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

The algorithm I want to add here is one of the Supervised Learning algorithm in Machine Learning that is used for both regression and classification. The algorithm separates the datapoints by making an optimal hyperplane.
The one SVM is added is in R and I want to do it in Python.

**Comment by ZoranPandovski** [comment]
Sure.

**Comment by taneemishere** [comment]
It's already done [here](https://github.com/ZoranPandovski/al-go-rithms/pull/2516) please review it and let me know, I'm waiting for 4 days. As you said before to add it to machine learning directory and I did that but then I didn't get any reply over when I did it.
