### ISSUE TITLE
Cleanup direcotries

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#2568]
There are too many files that are not inside the corresponding directory. I need help to move them e.g there could be bublesort.py in the root directory and it should be moved in sort/buble_sort/python/bublesort.py. Also, there are a lot of data_structure files that need to be moved etc. If you move the file please make share you move only one per PR so I can review it. Thanks

**Comment by Rac-Ro007** [comment]
@ZoranPandovski , please do have a check on following pr #2581, Thanks in advance (Grateful if u can attach hacktoberfest-accepted label to pr)
I would like to help u with the directories issue and sort all of them in their respective position, Can u assign me the issue it will be helpful that way.
