### ISSUE TITLE
Can we eliminate or fix the failing Page Build jobs?

### ISSUE THREAD

**Issue by cclauss** [ZoranPandovski/al-go-rithms#2640]
These are making our pull request merges fail...

<img width="1063" alt="Page Build is failing" src="https://user-images.githubusercontent.com/3709715/97175424-c5bc1080-1793-11eb-89f0-1f7a257636e3.png">

**Comment by ZoranPandovski** [comment]
I just remove that. Maybe I need to work on a way to display all of the implementations as separate pages in GitHub pages in the future.
