### ISSUE TITLE
Sort, search, greedy algorithms

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#271]
We need more sort, search and greedy algorithms in any language. PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by rohitrango** [comment]
Can we also have an algorithm for generating all possible permutations of a string?

**Comment by Rajiv2605** [comment]
@ZoranPandovski I don't think minimax algorithm has been implemented yet. Can I work on it?

**Comment by vn17** [comment]
Would you be interested in a Java 8 implementation of the Histogram Equalization Algorithm?

**Comment by vn17** [comment]
Would you be interested in a Java 8 implementation of the Histogram Equalization Algorithm?

**Comment by Rajiv2605** [comment]
@vn17 I am not much well versed in Java but can do in C++.

**Comment by vn17** [comment]
@Rajiv2605 Great! I've created a PR #343 for Java. I've added the file at `image_processing/histogram_equalization/java/HistogramEqualization.java`. So, it would be good if you can add your code at `image_processing/histogram_equalization/cpp/HistogramEqualization.cpp`.

**Comment by Rajiv2605** [comment]
@vn17 That sounds great! I will do it.

**Comment by Daman98** [comment]
Would you be interested in C++ implementation of BInomialHeap? It is not there in list

**Comment by Rajiv2605** [comment]
@Daman98 I'll first finish histogram equalization and then come to this
