### ISSUE TITLE
C++ code to count frequency of elements in array

### ISSUE THREAD

**Issue by priyanshu-28** [ZoranPandovski/al-go-rithms#2738]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

Added C++ code to count frequency of elements in array 

#2498

**Comment by avyayjain** [comment]
pls make it for hacktoberfest

**Comment by priyanshu-28** [comment]
How can I do that can you please help me?
