### ISSUE TITLE
Calculating Unique Numbers in An Array (Bit-Wise Trick)

### ISSUE THREAD

**Issue by adityaag24** [ZoranPandovski/al-go-rithms#2815]
**This is a(n):**

- [X] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

This issue is a set of algorithms where you are given an array and you need to find the unique number in that array in one pass of the array - O(n) algorithm.

**Comment by itsmeAnubhab** [comment]
would like to do this, please assign it to me.
