### ISSUE TITLE
 Lint Action not approving our PR's.

### ISSUE THREAD

**Issue by rishabh99-rc** [ZoranPandovski/al-go-rithms#2841]
### Lint Action not approving our PR's. (lint_python / lint_python (pull_request) Failing after 26s — lint_python)

* @ZoranPandovski, since you have merged the PR #2833 therefore now the lint action is not approving our PR's. I guess there was some issue with @PallaviPareek PR. Now since you have merged it, therefore even we are facing the same. 

**Details:**
The same issue is being faced by me & the following PRs : #2838 #2835 

I am even attaching my ss so that you come to know about the details. It would be great if you could kindly do the needful. 
Thanks in advance.

<img width="1440" alt="Screenshot 2021-10-08 at 1 05 14 AM" src="https://user-images.githubusercontent.com/55506770/136452786-b4035f8c-90d8-4598-a89a-8ed916a19e57.png">

**Comment by ZoranPandovski** [comment]
The linter should run only for python PR, but there is some issues in the action. Maybe I can exclude that for now

**Comment by rishabh99-rc** [comment]
> The linter should run only for python PR, but there is some issues in the action. Maybe I can exclude that for now

Yeah, that would be great, thanks.
