### ISSUE TITLE
Pre Order Traversal of Binary Tree : Recursive

### ISSUE THREAD

**Issue by kavania2002** [ZoranPandovski/al-go-rithms#2905]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

A Recursive Code of Pre Order Traversal of Binary Tree in C++.

**Comment by koffy1** [comment]
I'll change it for this issue instead ZoranPandovski/al-go-rithms#2908

**Comment by BobinMathew** [comment]
Is this issue still open for PR?
