### ISSUE TITLE
DFS in Javascripts

### ISSUE THREAD

**Issue by Kaid00** [ZoranPandovski/al-go-rithms#3016]
**This is a(n):**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

I would like to contribute an implementation of DFS in javascript

**Comment by Suraj1199** [comment]
Since @Kaid00 did not work on it for the last 10 days I decided to create a PR (#3172) that closes the issue. Please have a look.
