### ISSUE TITLE
New algorithm, data structures or puzzles

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#308]
Just make new PR with algorithm, data structures or puzzle implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by riyapannu7** [comment]
Can i add implementation of stacks using linked lists in C++?

**Comment by riyapannu7** [comment]
Can i add implementation of splay trees in C++?

**Comment by ZoranPandovski** [comment]
@riyapannu7 Yes, go ahead

**Comment by 8shubham** [comment]
Can I add a new algorithm for finding Lowest Common Ancestor in C++.

**Comment by Abhishek2019** [comment]
Can I add Best-First-Search algorithm ?

**Comment by lavinajain** [comment]
Can I add geometry implementations like Convex Hull I can't find the geometry section here. Shall I make one?

**Comment by 8shubham** [comment]
Can I add implementation of Disjoint Set Union in Data Structure section ?

**Comment by ZoranPandovski** [comment]
@lavinajain Yes, add geometry section or use math

**Comment by ZoranPandovski** [comment]
@8shubham Sure
