### ISSUE TITLE
Cleanup directories :broom: 

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#3162]
There are too many files that are not inside the corresponding directory. I need help to move them e.g there could be bublesort.py in the root directory and it should be moved in sort/buble_sort/python/bublesort.py. Also, there are a lot of data_structure files that need to be moved etc. If you move the file please make share you move only one per PR so I can review it. Thanks

**Comment by hritikvalluvar** [comment]
Hi, I would be help. Since I'm new to open source, can you explain what explain a bit more?
