### ISSUE TITLE
Longest word in a Sentence in cpp

### ISSUE THREAD

**Issue by Pranshu321** [ZoranPandovski/al-go-rithms#3230]
**This is a problem based on string concepts**
### Problem Statement
**Given a string, we have to find the longest word in the input string and then display the length of that word.**

```
Input: A hacktober fest contribution
Output: The longest word in a sentence is computer having length 12
```

- [x] New algorithm

**Details:**

In this, I will explain how we can find the largest word in a sentence with the most optimized approach.

- Problem Statement
- Useful comments
- Beginner-friendly code style
- Sample Input and Output

**Comment by Pranshu321** [comment]
@ZoranPandovski can you please , assign this issue to me.

**Comment by Siddharth9890** [comment]
@Pranshu321 and @ZoranPandovski i can do this in java language once you are done with c++

**Comment by ZoranPandovski** [comment]
Sure @Siddharth9890

**Comment by Pranshu321** [comment]
> @Pranshu321 and @ZoranPandovski I can do this in java language once you are done with c++

@Siddharth9890 after your contribution let me know so that I will close this issue.
