### ISSUE TITLE
Add new algorithm, data structures or puzzle

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#344]
Just make new PR with algorithm, data structures or puzzle implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by aadityakhare** [comment]
hello, I'd like to be a contributor to this issue. Please assign me.

**Comment by aadityakhare** [comment]
@ZoranPandovski Please review my PR.
