### ISSUE TITLE
Need tests for algorithms

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#376]
There are algorithms implementations that are missing tests. PR's are welcome

**Comment by h44rd** [comment]
Can I take this up, @ZoranPandovski ?

**Comment by callensm** [comment]
@h44rd unless you plan on writing tests for all algorithms in the repository, this is going to be an ongoing issue with several PRs.

**Comment by h44rd** [comment]
I don't think I'll be able to write for all of them, but I could start with some algorithm for now. Which one should I write the tests for?

**Comment by h44rd** [comment]
I would prefer histogram equalization if it's not done already.

**Comment by ZoranPandovski** [comment]
@h44rd Just choose one that you can execute and make PR's thanks

**Comment by h44rd** [comment]
So how do I write the tests, a little trouble starting up.

**Comment by raiman264** [comment]
I'm also interested on write test for js algorithms, is there some sort of guidelines to write the test, automation or something? or anything that can be manually run and prints a result is fine?

**Comment by ZoranPandovski** [comment]
@raiman264 You can use jasmin, but simple console.assert is ok too

**Comment by ZoranPandovski** [comment]
@h44rd Just assert that for e.g search or sort  for particular algorithm is ok
