### ISSUE TITLE
add queue in any language

### ISSUE THREAD

**Issue by tbhaxor** [ZoranPandovski/al-go-rithms#412]
i am adding a queue implementation in `csharp` at _data_structures/Queue_ with branch **queue_cs**

**Comment by ZoranPandovski** [comment]
Also we need other data structures

**Comment by tbhaxor** [comment]
:+1:

**Comment by hemantyadaviitg2016** [comment]
I want to add add stacks queue in c

**Comment by keshav48484848** [comment]
I want to add circular queue in C++
