### ISSUE TITLE
Sort, search, greedy algorithms in any language

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#483]
We need more sort, search and greedy algorithms in any language. PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by theyselim** [comment]
Which algorithms exactly? Should I just implement one e.g. merge sort, quick sort, binary search? or all?

**Comment by ZoranPandovski** [comment]
Yes choose whatever you want @theyselim
