### ISSUE TITLE
Link to "graphs" redirects to an error page

### ISSUE THREAD

**Issue by TefiC** [ZoranPandovski/al-go-rithms#487]
Hi, when I clicked on this link I was redirected to an error page.

![algorithm link bug](https://user-images.githubusercontent.com/16888172/31852258-bedd866e-b642-11e7-91ce-8b8d05105c3c.PNG)

I would like to send a pull request with this fix. Could you please tell me where should this link point to?

Thank you 😄

**Comment by leschlogl** [comment]
Theoretically: "data_structures/Graphs", but the guys created "/graphsearch/" for Graph search algorithms. If I were you, I would merge these two directories into "/data_strucutres/graphs"

**Comment by ZoranPandovski** [comment]
Yes @TefiC please fix that . Thanks

**Comment by TefiC** [comment]
Hi @ZoranPandovski , I sent the PR #502 with this fix. I combined both directories like @leschlogl suggested.
