### ISSUE TITLE
We need more data structures, algorithms, puzzles

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#535]
Just make new PR with algorithm, data structures or puzzle implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by ArighnaIITG** [comment]
I am on it.

**Comment by ananyasethi56** [comment]
i would like to do data structure algorithms

**Comment by ZoranPandovski** [comment]
Sure, go ahead @ananyasethi56
