### ISSUE TITLE
Space after "java" in path.

### ISSUE THREAD

**Issue by TefiC** [ZoranPandovski/al-go-rithms#550]
Hi, there's a space in the path `math/automorphic_numbers/java /AutomorphicNumber.java:` after `java` that's causing an error to fetch changes from the repository.

![space in path 2](https://user-images.githubusercontent.com/16888172/31891327-0fccfc02-b7d4-11e7-8775-e53ab68a355e.PNG)

**Comment by ZoranPandovski** [comment]
Can you fix that ? Thanks

**Comment by TefiC** [comment]
Hi @ZoranPandovski , I sent pull request #551 with this fix.
