### ISSUE TITLE
New algorithms, data structures, ciphers or puzzle implementations

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#587]
Just make new PR with algorithm, data structures, ciphers or puzzle implementation. Language doesn't matter.
Follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by aditya81070** [comment]
I am new to open source and am trying to contribute in projects.
I have added a math puzzle named Noidea in math directory. Please give it a look.

**Comment by AKS1996** [comment]
i guess matlab codes will also do, #595
