### ISSUE TITLE
New sort algorithms

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#59]
We need more sort algorithms in any language. PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by akshitgrover** [comment]
@ZoranPandovski Insertion sort in javascript, ok?

**Comment by MadhavBahlMD** [comment]
@ZoranPandovski i am doing quicksort in javascript, ok?

**Comment by admiralnelson** [comment]
quick sort in java coming trough

**Comment by Gupta-shifali** [comment]
@ZoranPandovski I am doing quicksort in c++?

**Comment by ZoranPandovski** [comment]
@Gupta-shifali Yes sure

**Comment by SUCHITA-MEHTA** [comment]
I am willing to do bubble sort using python

**Comment by ZoranPandovski** [comment]
@SUCHITA-MEHTA Ok just make PR
