### ISSUE TITLE
Missing short documentations about algorithm

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#709]
Most of the algorithms, ciphers and data structures are missing documentations. Also you can add more info to the existing once. PR's are welcome

**Comment by amirags** [comment]
On it! Will start on adding the basic structure that can be adapted later on as required.

**Comment by amirags** [comment]
Added #718, do check if its alright. Thanks! Will continue with remaining ones.

**Comment by ZoranPandovski** [comment]
Thanks @amirags
