### ISSUE TITLE
Sorting Algorithm in Different launguages

### ISSUE THREAD

**Issue by thesachinmittal** [ZoranPandovski/al-go-rithms#713]
**This is a(n):**

- [x] New algorithm

**Details:**

- [ ] Bubble Sort
- [ ] Selection Sort  
- [ ] Insertion Sort 
- [ ] Quick Sort 
- [ ] Merge Sort 
- [ ] Heap Sort
- [ ] Other Sorting Algorithms

**Comment by thesachinmittal** [comment]
Assign it to me.

**Comment by ak-iitjm** [comment]
I can insert some algorithms in cpp and java
