### ISSUE TITLE
Search algorithms 

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#76]
We need more Search algorithms in any language. PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by vaibhavagarwal220** [comment]
Can i be assigned for this.

**Comment by Gupta-shifali** [comment]
Can i implenment linear search in c @ZoranPandovski ??

**Comment by ZoranPandovski** [comment]
@Gupta-shifali Sure go ahead :)

**Comment by abhinavraj0123456789** [comment]
Can I implement linear search in JavaScript?

**Comment by ZoranPandovski** [comment]
@abhinavraj0123456789 Sure go ahead
