### ISSUE TITLE
New data structures

### ISSUE THREAD

**Issue by ZoranPandovski** [ZoranPandovski/al-go-rithms#77]
Currently we  got few data structures so new PR's are welcome. Just follow the structure : https://github.com/ZoranPandovski/al-go-rithms#contribution.

**Comment by vaibhavagarwal220** [comment]
Can i be assigned for this

**Comment by polinag96** [comment]
Can I be assigned for linked list in c++?

**Comment by Gupta-shifali** [comment]
@ZoranPandovski Can I implement circular linked list in c++?

**Comment by hackbansu** [comment]
i have added generic type linked list in java with test file. please accept pull request #77

**Comment by akshitgrover** [comment]
@ZoranPandovski I am working on Missionaries and cannibal problem, Maybe I can Create a PR for that too?

**Comment by ZoranPandovski** [comment]
@akshitgrover Sure, go ahead.

**Comment by Gupta-shifali** [comment]
@ZoranPandovski I added circular linked list implementation in c++, pls accept my pr
