### ISSUE TITLE
Add section titles for online course providers on README

### ISSUE THREAD

**Issue by TefiC** [ZoranPandovski/al-go-rithms#856]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

Hi! I would like to propose adding section titles for online course providers to improve readability and scalability if the provider adds more courses on Algorithms.

This is what I propose for each provider (Coursera, Udacity, EdX and new ones to be added):

![image](https://user-images.githubusercontent.com/16888172/35483107-8490a638-0414-11e8-8646-e45442b16ed0.png)

 If you would like to implement this change, I would like to implement it and submit a Pull Request.

**Comment by ZoranPandovski** [comment]
Thanks @TefiC , that would be useful, can you make PR ?

**Comment by TefiC** [comment]
@ZoranPandovski Yes, I will make a PR with this change.

**Comment by ZoranPandovski** [comment]
@TefiC please feel free to add new improvements

**Comment by TefiC** [comment]
@ZoranPandovski Okay. Thank you very much.
