### ISSUE TITLE
Write unit tests for each algorithm you implement

### ISSUE THREAD

**Issue by rahulrana95** [ZoranPandovski/al-go-rithms#922]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**

We can write unit tests for the algorithms implemented in javascript language

**Comment by rahulrana95** [comment]
@rahulrana95

**Comment by ZoranPandovski** [comment]
Awesome @rahulrana95 , you can start with tests :)

**Comment by rahulrana95** [comment]
@ZoranPandovski I can start writing the tests for javascript language.
First I will set up the environment for writing unit tests for js language and add documentation to how to write tests.

**Comment by kindacoder** [comment]
hey @rahulrana95  how can I test the algorithms? Can you please help? I don't know how to test algorithms. Thanks in advance

**Comment by ZoranPandovski** [comment]
I will create generic issue for this. Thanks @rahulrana95
