### ISSUE TITLE
Want to add c++ Pointers tutorial

### ISSUE THREAD

**Issue by kindacoder** [ZoranPandovski/al-go-rithms#924]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**
I want to add c++ Pointers tutorial. Can I ? I have written beautiful tutorial that will help people to understand pointers better.

**Comment by kindacoder** [comment]
hey @ZoranPandovski please check I have uploaded the first part of the tutorial.

**Comment by ZoranPandovski** [comment]
@kindacoder  You can add more tutorials, I will close this issue.
