### ISSUE TITLE
LinkedList Cycle Detection in C++

### ISSUE THREAD

**Issue by shauryauppal** [ZoranPandovski/al-go-rithms#957]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by shauryauppal** [comment]
@ZoranPandovski If you allow a PR for this, I will implement and send a PR.

**Comment by ZoranPandovski** [comment]
Sure @shauryauppal

**Comment by shauryauppal** [comment]
@ZoranPandovski Task Complete
