### ISSUE TITLE
Fixing directories

### ISSUE THREAD

**Issue by Varpie** [ZoranPandovski/al-go-rithms#959]
**This is a:**
- [ ] New algorithm
- [ ] Update to an existing algorithm
- [ ] Error
- [x] Proposal to the Repository

**Details:**
A lot of directories do not follow the recommended structure `algorithm_name/language-name/file_name.extension`, sometimes the program is directly in the `algorithm_name` directory.

An other interesting thing to do would be adding README.md files for each `algorithm_name` directory, explaining how the algorithm works, as it has been done in most sort algorithms (see #919)

Making such changes would allow for a cleaner repository, as well as allowing beginners to understand how to make a pull request in a useful scenario.

**Comment by ZoranPandovski** [comment]
@Varpie You can start with this. Just follow the Contribution guide and fix all of the files that are in wrong directories. Thanks
